### ISSUE TITLE
Show how to add the icon to Firefox toolbar; add a subentry to the Tools menu

### ISSUE THREAD

**Issue by peter-kehl** [nohamelin/simple-locale-switcher#10]
Hi Nohamelin,

thank you Simple Locale Switcher. Can I suggest that some people may not know how to add an icon/button to their Firefox toolbar. Please, could you add screenshot(s) and some steps about it to https://addons.mozilla.org/en-US/firefox/addon/simple-locale-switcher/. E.g. steps like
- right click at/near any button in Firefox toolbar (but not at search fields).
- select 'Customize...' from the dropdown menu
- drag & drop 'Language' button <put icon here> to the toolbar

Also, a bigger suggestion: It could be worth to add an entry in Firefox 'Tools' menu, which would show the language selector and configuration popup (if possible).

**Comment by nohamelin** [comment]
Hi Peter,
About the first, sure, it has become a recurrent question; I will add a mention in the add-on description linking to:
https://support.mozilla.org/kb/customize-firefox-controls-buttons-and-toolbars

Adding a new entry in the tools menu is possible, but I'm still unsure. I don't like how extensions clutters this not-easily-editable menu. But as since version 0.8.2 I removed the link to the language selector via the main options window of Firefox/Thunderbird, the keyboard accessibility was weakened, so this new entry via the menubar can help. I will think about it.

**Comment by nohamelin** [comment]
For now, I added a basic mention to the add-on description in AMO. More specific instructions will be added to the [user guide] (https://github.com/nohamelin/simple-locale-switcher/wiki/Simple-User-Guide#the-new-languages-toolbar-button) (soon, I expect...)

**Comment by nohamelin** [comment]
About overlaying the Tools menu: 
With the arrival of WebExtensions as unique accepted add-on model in release versions of Firefox, editing the tools menu will not be possible anymore. The general situation of Thunderbird and SeaMonkey about it is still uncertain. Anyway, I'm closing it.
